### ISSUE TITLE
(Owin / MVC5 / Integrated mode) is there another way to inject a request into the appDomainProxy?

### ISSUE THREAD

**Issue by elliottoberg** [i-e-b/MvcIntegrationTestFramework#5]
This is obviously related to another (closed) issue.  I am wanting to get tests running against an app which uses Owin / MVC5 / and IIS7 (integrated mode).

You probably already know, but the problem with MvcIntegrationTestFramework in this respect is the way it injects a request into the appDomainProxy (using HttpRuntime.ProcessRequest()).

HttpRuntime.ProcessRequest() is not supported in IIS7 integrated mode.   Since you have worked on this, I wonder if you know any other way to inject a request into the appDomainProxy? (something compatible with Integrated mode)

Scouring google doesn't yield anything obvious and I am not familiar enough with the Http namespace to know of a workaround.  I know we can create Http Handlers and Http Modules in Integrated mode... but it seems they don't provide the access for injecting a request?  

Sorry for digging up this topic lol :)
I have to support legacy code or else I would just give up on these tests and write my apps in .net core!

Thank you for any time or information you can give!

**Comment by StephanLuis** [comment]
Sorry I don't have any useful information for your situation.  I had
extension methods that required in depth mocking of the HTTP request, I
implemented a work around so that the controller's response didn't call the
extension method.  A solution that's not ideal, but I'm shooting to upgrade
to core as soon as I can.  From what I recall the
MvcIntegrationTestFramework was only useful for very specific (older)
setups.

**Comment by elliottoberg** [comment]
Thanks for your reply.  I will make do for now.
